$(document).ready(function()
{
    $("#room1").on("click",function(event)
    {
        document.getElementById('carouselExampleFade').remove();
        cargarTematica("classroom","marineanimal.html")
    })
    $("#room2").on("click",function(event)
    {
        document.getElementById('carouselExampleFade').remove();
        cargarTematica("classroom","neighborhood.html")
    })
    $("#room3").on("click",function(event)
    {
        document.getElementById('carouselExampleFade').remove();
        cargarTematica("classroom","dance.html")
    })
    $("#room4").on("click",function(event)
    {
        document.getElementById('carouselExampleFade').remove();
        cargarTematica("classroom","preposiciones.html")
    })
    $("#room5").on("click",function(event)
    {
        document.getElementById('carouselExampleFade').remove();
        cargarTematica("classroom","solarsystem.html")
    })
    $("#room6").on("click",function(event)
    {
        document.getElementById('carouselExampleFade').remove();
        cargarTematica("classroom","shooting.html")
    })
    
    
})